
runtime: nodejs18

instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 0

env_variables:
  NODE_ENV: "production"
  # Replace these with your actual Cloud SQL instance details in your deployment pipeline
  # DO NOT COMMIT REAL PASSWORDS TO GITHUB
  DB_HOST: "127.0.0.1" 
  DB_USER: "root"
  DB_PASSWORD: "password_here"
  DB_NAME: "chatkara"
  DB_PORT: "3306"
  # Uncomment the line below if using Unix Sockets on Cloud Run (Recommended over DB_HOST)
  # INSTANCE_CONNECTION_NAME: "your-project-id:region:instance-name"
