runtime: nodejs18

instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 0

env_variables:
  NODE_ENV: "production"
  DB_HOST: "34.131.187.182"
  DB_USER: "test"
  DB_PASSWORD: "rest"
  DB_NAME: "chatkara"
  DB_PORT: "3306"
  # Uncomment the line below if using Unix Sockets on Cloud Run (Recommended over DB_HOST)
  # INSTANCE_CONNECTION_NAME: "your-project-id:region:instance-name"
