runtime: nodejs18

instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 0

env_variables:
  NODE_ENV: "production"
  DB_HOST: "db-mysql-blr1-87083-do-user-28234243-0.l.db.ondigitalocean.com"
  DB_USER: "doadmin"
  DB_PASSWORD: "AVNS_gVx0SkJzKnnNqQxaS0e"
  DB_NAME: "defaultdb"
  DB_PORT: "25060"
  # Uncomment the line below if using Unix Sockets on Cloud Run (Recommended over DB_HOST)
  # INSTANCE_CONNECTION_NAME: "your-project-id:region:instance-name"
